# Generated by Django 5.1 on 2024-08-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_shipped_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
